FROM ubuntu:16.04

RUN apt-get update && apt-get install -y doxygen graphviz

COPY doc /club/doc
COPY src /club/src

WORKDIR /club

RUN doxygen doc/Doxyfile

FROM nginx:alpine

COPY --from=0 /club/doc/doxygen/html /usr/share/nginx/html
